In [471]:
import pandas as pd
df=pd.read_csv("big_data.csv")

In [472]:
#-----------checking DUPLICATE VALUES-----------

In [473]:
df.duplicated(subset='customer_id').sum()

np.int64(95500)

In [474]:
df.duplicated(subset='product_id').sum()

np.int64(99500)

In [475]:
#--------Removing Duplicate Values----------

In [476]:
#------from customer_id-----

In [477]:
df.duplicated(subset=['product_id','customer_id']).sum()

# no duplicate values in customer id ,order id and ,product id

np.int64(1460)

In [478]:
#---------Fixing Null Value------------
df.dropna()

,order_id,customer_id,product_id,order_date,status,payment_method,city,quantity,price,total_amount
1,1001,C1900,P0136,5/14/2024,Delivered,Credit Card,Bangalore,4,43945,175780
2,1002,C3595,P0132,3/13/2024,Returned,Debit Card,Kolkata,1,2365,2365
5,1005,C1900,P0766,11/16/2023,Returned,Cash on Delivery,Kolkata,4,32244,128976
7,1007,C2036,P0686,8/9/2023,Returned,Credit Card,Mumbai,1,40341,40341
8,1008,C1900,P0928,8/14/2023,Cancelled,Cash on Delivery,Kolkata,3,48477,145431
...,...,...,...,...,...,...,...,...,...,...
100493,47036,C1894,P0608,2/6/2024,Cancelled,Cash on Delivery,Delhi,4,13367,53468
100494,34184,C2816,P0095,5/4/2024,Cancelled,Credit Card,Bangalore,1,33721,33721
100495,9820,C2296,P0538,12/31/2023,Delivered,UPI,Bangalore,2,2576,5152
100496,36258,C0438,P0198,6/3/2023,Pending,Debit Card,Delhi,1,42880,42880
100499,8192,C4457,P0663,1/3/2023,Delivered,Credit Card,Mumbai,4,45561,182244

In [479]:
#-----------Removing Null Values----------------

In [480]:
df.dropna(inplace=True)
#df.isnull().sum()
#-----------no NULL VALUE -----------
df.isnull().sum()

order_id          0
customer_id       0
product_id        0
order_date        0
status            0
payment_method    0
city              0
quantity          0
price             0
total_amount      0
dtype: int64

In [481]:
#-------checking NUN value

#df.isnull().sum(axis=0)
#df.isnull().any()

In [482]:
#----------Fixing Date-----
df['order_date']=pd.to_datetime(df['order_date'])

In [483]:
#-----------counting upi-------
#df['upi']=df.loc[df['payment_method']=="UPI",'payment_method'].count()
#df
df=df[["order_id","customer_id","product_id","order_date","status","payment_method","city","price","total_amount"]]

In [484]:
#-----------Average from each------------------

average_df =df.groupby('payment_method')['total_amount'].agg(['sum','mean']).reset_index()
#average_df2 =df.groupby('payment_method')['total_amount'].mean().rename('average_amount')

#new_dff=pd.merge(df,average_df,average_df2,on='payment_method')
average_df.columns= ['payment_method','total_amount','average_amount']
average_df






#-----Sheperate  sheet for only Payments details----

 #-----All Paymets----------
df1=df[['customer_id','order_id','payment_method','total_amount']]
df1
upi_df1=df1



#------UPI Details------------------

df2=df[df['payment_method']=="UPI"]
df2=df2[['order_id','total_amount']]
upi_df2=df2

#---------Credit card Details------------
df3=df[df['payment_method']=="Credit Card"]
df3=df3[["order_id","payment_method",'total_amount']]
upi_df3=df3

#----------Debit Card Details---------------
df4=df[df['payment_method']=="Debit Card"]
df4=df4[["order_id","payment_method",'total_amount']]
upi_df4=df4


#------------Total Income----------------
#Payment_df= df.groupby('payment_method')['total_amount'].sum()
#payment_df.loc[len(payment_df)]=['Total',payment_df['total_amount'].sum()]

In [485]:
    #--------top selling amounts----------

df['months']=df['order_date'].dt.to_period('M')
df_monthly_sale=df.groupby('months')['total_amount'].sum().reset_index()

df_high_monthly_sale=df_monthly_sale.sort_values(by="total_amount",ascending=False).reset_index(drop=True)

df_high_monthly_top10=df_high_monthly_sale.loc[0:10,["months","total_amount"]]
df_high_monthly_top10=df_high_monthly_top10.rename(columns={"total_amount":"Heighest_selling_amount",
                                      "months":"top_selling_months"
                                     
                                     })
df_monthly_sale_average=df.groupby(by="months")["total_amount"].mean().reset_index()
df_monthly_sale_average=df_monthly_sale_average.sort_values(by="total_amount",ascending=False).reset_index(drop=True)

#merged_df=pd.merge(df_monthly_sale,df_monthly_sale_average,on='months',how='outer')
#all_payment_info=pd.merge(merged_df,df_high_monthly_top10,left_on='months',right_on='top_selling_months',how='outer')

#df=df[["order_id","customer_id","product_id","order_date","status","payment_method","city","price","total_amount"]]
#df_high_monthly_top10
#df_high_monthly_sale


#------top selling product---------

top_products=df.groupby('product_id')['total_amount'].sum().reset_index()
top_products=top_products.sort_values(by="total_amount",ascending=False).reset_index(drop=True)
top10_selling_products=top_products.loc[0:9,['product_id','total_amount']]
#top_products
#top10_selling_products

In [486]:
#-------------top_10_customer_____
top10_customer=df.groupby("customer_id")['total_amount'].sum().reset_index()
top10_customer=top10_customer.sort_values(by="total_amount",ascending=False).head(10)
top10_customer=top10_customer.reset_index(drop=True)
top10_customer
df

,order_id,customer_id,product_id,order_date,status,payment_method,city,price,total_amount,months
1,1001,C1900,P0136,2024-05-14,Delivered,Credit Card,Bangalore,43945,175780,2024-05
2,1002,C3595,P0132,2024-03-13,Returned,Debit Card,Kolkata,2365,2365,2024-03
5,1005,C1900,P0766,2023-11-16,Returned,Cash on Delivery,Kolkata,32244,128976,2023-11
7,1007,C2036,P0686,2023-08-09,Returned,Credit Card,Mumbai,40341,40341,2023-08
8,1008,C1900,P0928,2023-08-14,Cancelled,Cash on Delivery,Kolkata,48477,145431,2023-08
...,...,...,...,...,...,...,...,...,...,...
100493,47036,C1894,P0608,2024-02-06,Cancelled,Cash on Delivery,Delhi,13367,53468,2024-02
100494,34184,C2816,P0095,2024-05-04,Cancelled,Credit Card,Bangalore,33721,33721,2024-05
100495,9820,C2296,P0538,2023-12-31,Delivered,UPI,Bangalore,2576,5152,2023-12
100496,36258,C0438,P0198,2023-06-03,Pending,Debit Card,Delhi,42880,42880,2023-06
100499,8192,C4457,P0663,2023-01-03,Delivered,Credit Card,Mumbai,45561,182244,2023-01

In [487]:
#-----------Inique Customers
df_unique_customer=pd.DataFrame(df['customer_id'].unique(),columns=['customer_id'])
df_unique_customer

#-----------repet_customers--------------
repeat_customer=df.groupby('customer_id')['order_id'].count().reset_index()
repeat_customer=repeat_customer[repeat_customer['order_id']>1]
repeat_customer.rename(columns={'order_id':'order_count'},inplace=True)
repeat_customer=repeat_customer.sort_values(by='order_count',ascending=False)
print(repeat_customer)

     customer_id  order_count
4320       C4321           34
2261       C2262           29
4976       C4977           29
2696       C2697           28
1651       C1652           28
...          ...          ...
3211       C3212            4
2973       C2974            4
3973       C3974            3
1117       C1118            3
3247       C3248            3

[5000 rows x 2 columns]

In [488]:
#-----------common Order Status-------------
df_status_count=df['status'].value_counts().reset_index()
df_status_count.columns=['status','status_count']
df_status_count=df_status_count.sort_values(by="status_count",ascending=False)
df_status_count

      status  status_count
0  Cancelled         17458
1   Returned         17299
2  Delivered         17226
3    Pending         17059

In [489]:
#-----------cancelation rate
df_total_order=df['order_id'].count()
df_cancelled_order=df[df['status']=="Cancelled"]['status'].count()
cancellation_rate=(df_cancelled_order/df_total_order)*100
cancellation_rate=round(cancellation_rate,2)

cancel_df=pd.DataFrame({'cancellation_rate':[cancellation_rate]})


cancel_df

   cancellation_rate
0              25.29

In [ ]:
#-------sale by city-----------
df_top_selling_city=df.groupby('city')['total_amount'].sum().reset_index()

df_top_performing_city=df_top_selling_city.sort_values(by="total_amount",ascending=False).reset_index()
df_top_performing_city
df_top_selling_city







#-----Creating Sheets-------------


with pd.ExcelWriter("Payment.xlsx",engine='openpyxl') as writer:
    upi_df1.to_excel(writer,sheet_name="All Payment",index=False)
    upi_df2.to_excel(writer,sheet_name="Upi info",index=False)
    upi_df3.to_excel(writer,sheet_name="Credit card Details",index=False)
    upi_df4.to_excel(writer,sheet_name="Debit card Details",index=False)
    average_df.to_excel(writer,sheet_name="Average Amounts",index=False)
    df_monthly_sale.to_excel(writer,sheet_name="Monthly_selling",index=False)
    df_monthly_sale_average.to_excel(writer,sheet_name="Average sale for months",index=False)
    df_high_monthly_top10.to_excel(writer,sheet_name="top Sellings Months",index=False)
    top_products.to_excel(writer,sheet_name="top_selling_products",index=False)
    top10_selling_products.to_excel(writer,sheet_name="top10_selling_products",index=False)
    top10_customer.to_excel(writer,sheet_name="top10_customer",index=False)
    df_unique_customer.to_excel(writer,sheet_name="df_unique_customer",index=False)
    df_unique_customer.to_excel(writer,sheet_name="df_unique_customer",index=False)
    repeat_customer.to_excel(writer,sheet_name="repeat_customers",index=False)
    df_status_count.to_excel(writer,sheet_name="df_status_count",index=False)
    cancel_df.to_excel(writer,sheet_name="cancelation_rate",index=False)
    df_top_selling_city.to_excel(writer,sheet_name="top_selling_city",index=False)
    df_top_performing_city.to_excel(writer,sheet_name="df_top_performing_city",index=False)

In [ ]:
exactly_df=pd.read_excel("Payment.xlsx",sheet_name="top_selling_city")
exactly_df

In [ ]:
#Payment_df= df.groupby('payment_method')['total_amount'].sum()
#total_df=Payment_df.sum()
#total_df

In [ ]:
#------------finding total sales with months

In [ ]:
'''df['months']=df['order_date'].dt.to_period('M')
df_monthly_sale=df.groupby('months')['total_amount'].sum().reset_index()

df_high_monthly_sale=df_monthly_sale.sort_values(by="total_amount",ascending=False).reset_index()

df_high_monthly_top10=df_high_monthly_sale.loc[0:10,["months","total_amount"]]
df_high_monthly_top10.rename(columns={"total_amount":"Heighest_selling_amount",
                                      "months":"top_selling_months"
                                     
                                     },inplace=True)

#df=df[["order_id","customer_id","product_id","order_date","status","payment_method","city","price","total_amount"]]
df_high_monthly_top10'''
#df_high_monthly_sale

In [ ]:
df.reset_index(drop=True,inplace=True)
with pd.csv("Amazon_data_frame.csv")

In [ ]:
df